application: learnaapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /save
  script: main.app

- url: /get/(.*)
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /examples
  static_files: build/index.html
  upload: build/index.html
- url: /learna
  static_files: build/index.html
  upload: build/index.html
- url: /learna/(.*)
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/
- .vs_code/
- src/
- public/
- .DS_Store
